### ISSUE TITLE
Querystring /w clubid&articleno

### ISSUE THREAD

**Issue by d51r3verse** [joyfuI/NaverCafePass#3]
Some new? URIes
hxxps://x/ArticleRead.nhn?clubid=###&page=1&boardtype=L&articleid=###&referrerAllArticles=true
hxxps://x/ArticleRead.nhn?clubid=###&articleid=###&page=1&boardtype=L
hxxps://x/ArticleRead.nhn?clubid=###&articleid=###&page=1&boardtype=L&menuid=###

```(/\/ArticleRead\.nhn\?clubid=/).test(details.url)```
I tried to modify querystring on the fly like [this](https://stackoverflow.com/a/42629059)
* Extract ```articleid``` like above
* Extract ```cafeInfo``` from HTML
* Then, Redirect to /cafeInfo/articleid
But, No idea to integrate new redirects with extra dummy referer.

**Comment by joyfuI** [comment]
I used Google Translator because I can not speak English. please understand.
We have been updated to work on the `ArticleRead.nhn` page by adding redirects based on your ideas.
However, synchronous XMLHttpRequest has been used in this process, and this causes a warning message. There is no way to change it to asynchronous...

-----
제가 영어를 못 해서 구글 번역기를 사용한 점. 양해 바랍니다.
알려주신 아이디어를 바탕으로 리다이렉션을 추가하여 `ArticleRead.nhn` 페이지에서도 작동하도록 업데이트되었습니다.
다만 이 과정에서 동기식 XMLHttpRequest가 사용되었는데 이것 때문에 경고 메시지가 하나 뜨네요. 비동기로 바꿀 방법이 없으려나...
